---

############################
# terraform playbook       #
############################

- hosts: aws
  strategy: linear
  gather_facts: yes
  become: yes

  tasks:
    - name: Install the latest apache2
      package:
        name:
          - apache2