---

############################
# terraform playbook       #
############################

- hosts: localhost
  strategy: linear
  gather_facts: yes
  become: yes

  tasks:
    - name: Install the latest "{{item}}"
      package:
        name: "{{ item }}"
      loop: "{{ apps }}"