---

############################
# terraform playbook       #
############################

- hosts: aws
  strategy: linear
  gather_facts: yes
  become: yes
  roles:
    - name: Install docker
      role: role_labo_docker
      when: '"docker" in apps'

    - name: Install node exporter
      role: undergreen.prometheus-node-exporter
      vars:
        prometheus_node_exporter_version: 1.0.1
        prometheus_node_exporter_enabled_collectors:
          - conntrack
          - cpu
          - diskstats
          - entropy
          - filefd
          - filesystem
          - loadavg
          - mdadm
          - meminfo
          - netdev
          - netstat
          - stat
          - textfile
          - time
          - vmstat
        prometheus_node_exporter_config_flags:
          'web.listen-address': '0.0.0.0:9100'
          'log.level': 'info'
      when: '"node-exporter" in apps'

  tasks:
      - name: install package
        package:
             name: apache2
        when :  '"apache2" in apps'