---

    - set_fact:
        path: "{{role_path}}"
    - name: Pass variables to role
      include_role:
           name: ansible.terraform.aws
      vars:
           terraform_files_path: "{{path}}/files/20.04"


# tasks file for ansible.terraform.aws.ubuntu
#    - name: remove old dynamic host file
#      file:
#          path: inventories/TARGET/hosts
#          state: absent
#    - name: create new dynamic host file
#      file:
#          path: inventories/TARGET/hosts
#          state: touch
#    - name: set vm_ip / name
#      set_fact:
#          vm_ip: "50.101.144.185sev"
#          vm_ip_name: "mock-labo"
#
#    - name: add retrieved IP to file
#      blockinfile:
#          path: "inventories/TARGET/hosts"
#          marker: ""
#          block: |
#            [dynamic_web]
#            {{ vm_ip }}
#          state: present